[env:m5sticks3]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    m5stack/M5Unified @ ^0.2.4
    bblanchon/ArduinoJson @ ^7.2.0
